### PR TITLE
picture change and small changes to ImageUpload

### PR DESCRIPTION
**Pull request by ziel5122**
changed React logo to Panafold logo. Changed some formatting. Edited ImageUpload code to make it more concise. Also removed Jest setup and dependencies.

### CODE REVIEW

**Comment by ziel5122** [comment]
O woops I messed up one thing in App.js

**Comment by araceli19** [comment]
Ok, so updates are good now?

**Comment by ziel5122** [comment]
css is a little funny because you wrote a rule for img

**Comment by ziel5122** [comment]
checking changes locally

**Review by araceli19 — APPROVED** [review]
I like the logo idea and the use of optionals. Everything else looks good.

**Comment by ziel5122** [comment]
Ok everything looks good now. Tested locally.

**Pull request merged**
